language: go

go:
  - 1.20.x
  - 1.21.x

before_script: >
  export CLOUDINARY_URL=$(bash scripts/get_test_cloud.sh);
  echo cloud_name: "$(echo $CLOUDINARY_URL | cut -d'@' -f2)"

script:
  - go test -v ./...

notifications:
  email:
    recipients:
      - sdk_developers@cloudinary.com
